# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 179bd8abd2d6eeb95a31081aaa6d6801b30f7cad3f832f8f43e75c7362f8fc36fb058d09c37d105640fb2d0a8ec69a2020763612457e54fc36683d3a8bbd5e6e

test:
  secret_key_base: 2286661e83bb865ade778d44422f2acf4a92ff531ce8a02c3de2622f13cde03ca934b0e135230649fe6d21cc616b2a416a35313a52b7a16ccd3300f8f5b6d38c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
